server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://lcnppvhambhvrk:8f134b3e84fd24d4b1927dc0710c0a334f8d10111d66e6fe2ad73e291a40c6fb@ec2-54-145-249-177.compute-1.amazonaws.com:5432/dcptobtb21fvab
    username: lcnppvhambhvrk
    password: 8f134b3e84fd24d4b1927dc0710c0a334f8d10111d66e6fe2ad73e291a40c6fb
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander
  version: 1.0
  termsOfService: http://swagger.io/terms
  licenseName: Apache 2.0
  url: http://springdoc.org


